--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BlockMagicDev/AdvancedItem
build-by-default: true
branches:
- main
projects:
  AdvancedItem:
    path: ""
    icon: "assets/images/icon.png"
...
